// Autogenerated by cbindgen

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace my_cool_rust_pkg {

extern "C" {

void greet(int32_t excitedness);

} // extern "C"

} // namespace my_cool_rust_pkg
