build:
  image: docker:20.10.16
  stage: build
  only:
    refs:
      - main
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/dev-core/jupiter/ros2_rust_fork:latest .
    - docker push $CI_REGISTRY/dev-core/jupiter/ros2_rust_fork:latest